on:
  pull_request:
    types: [opened,edited]
jobs:
  required_labels:
    runs-on: ubuntu-latest
    name: Required Labels
    steps:
      - name: Required Labels
        uses: pr-bot-test/required-labels@master
        with:
          labels: "doc-required, no-need-doc, doc"
          GITHUB_TOKEN: ${{ secrets.token }}
