name: Auto Labeling

on:
  issues:
    types:
      # Trigger the action only on relevant activity types.
      # It's actually not harmful to trigger the action on all activity types.
      - opened
      - edited
  pull_request:
    types:
      - opened
      - edited

# A GitHub token created for a PR coming from a fork doesn't have
# 'admin' or 'write' permission (which is required to add labels)
# To avoid this issue, you can use the `scheduled` event and run
# this action on a certain interval.
jobs:
  labeling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pr-bot-test/auto-labeling@master
        with:
          github-token: ${{ secrets.token }}
          label-pattern: '- \[(.*?)\] ?`(.+?)`' # matches '- [x] `label`'
  required_labels:
    runs-on: ubuntu-latest
    name: Required Labels
    needs: labeling
    steps:
      - name: Required Labels
        uses: pr-bot-test/required-labels@master
        with:
          labels: "doc-required,no-need-doc,doc"
          GITHUB_TOKEN: ${{ secrets.token }}
