name: Auto Labeling

on:
  pull_request:
    types:
      - opened
      - edited
      - labeled

  

# A GitHub token created for a PR coming from a fork doesn't have
# 'admin' or 'write' permission (which is required to add labels)
# To avoid this issue, you can use the `scheduled` event and run
# this action on a certain interval.
jobs:
  labeling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pr-bot-test/auto-labeling@master
        with:
          github-token: ${{ secrets.token }}
          label-pattern: '- \[(.*?)\] ?`(.+?)`' # matches '- [x] `label`'
